### ISSUE TITLE
.SetMinimumLevel() has no effect

### ISSUE THREAD

**Issue by OszkarOlah** [nreco/logging#13]
I use this implementation in a Core Console app without settings file. This is how I create a logger:
```
var lf = LoggerFactory.Create(builder =>
	{
		builder.SetMinimumLevel(LogLevel.Trace);
		builder.AddDebug();
		builder.AddConsole(c => c.DisableColors = false);
		builder.AddFile($"{logPath}\\SomeName_{DateTime.Now:yyyy-MM-dd_HH-mm-ss-ffff}.log")
			.SetMinimumLevel(LogLevel.Trace);
	});
_logger = lf.CreateLogger<Program>();
```
Is there a way to set the default log level to **LogLevel.Trace** programmatically?

**Comment by VitaliyMF** [comment]
Take a look to how "AddFile" extension method is implemented here: https://github.com/nreco/logging/blob/master/src/NReco.Logging.File/FileLoggerExtensions.cs

Instead of "AddFile" you may use:

```
builder.Services.Add(ServiceDescriptor.Singleton<ILoggerProvider, FileLoggerProvider>( 
	(srvPrv) => {
		return new FileLoggerProvider($"{logPath}\\SomeName_{DateTime.Now:yyyy-MM-dd_HH-mm-ss-ffff}.log", true) {  MinLevel = LogLevel.Trace  };
	}
));
```

This approach is not very intuitive in fact, and it might be more convenient to add MinLevel option to FileLoggerOptions. Let me know if this is what you're looking for.

**Comment by OszkarOlah** [comment]
Yes, that's what I wanted to achieve. Thanks for your quick response.
